### ISSUE TITLE
Improve CI

### ISSUE THREAD

**Issue by yunwei37** [eunomia-bpf/ebpm-template#1]
replace git clone with this:

```yaml
- name: Get compiler set
  uses: actions/checkout@v3
  with:
     repository: eunomia-bpf/ebpm-bootstrap
     submodules: true
```

see some commit CI failed.

And use realpath in Makefile, add a `/` after source locations.
